testJsonAccessTokenResponse = '''{
   "access_token": "NgA6ZcYI...ixn8bUQ",
   "token_type": "Bearer",
   "scope": "user-read-private user-read-email",
   "expires_in": 3600
}'''

testJsonSongResponse = """{
  "collaborative": false,
  "description": "Your daily update of the most viral tracks right now - Sweden.",
  "external_urls": {
    "spotify": "https://open.spotify.com/playlist/37i9dQZEVXbIPOivNiyjjS"
  },
  "followers": {
    "href": null,
    "total": 51358
  },
  "href": "https://api.spotify.com/v1/playlists/37i9dQZEVXbIPOivNiyjjS",
  "id": "37i9dQZEVXbIPOivNiyjjS",
  "images": [
    {
      "height": null,
      "url": "https://charts-images.scdn.co/assets/locale_en/viral/daily/region_se_large.jpg",
      "width": null
    }
  ],
  "name": "Viral 50 - Sweden",
  "owner": {
    "display_name": "spotifycharts",
    "external_urls": {
      "spotify": "https://open.spotify.com/user/spotifycharts"
    },
    "href": "https://api.spotify.com/v1/users/spotifycharts",
    "id": "spotifycharts",
    "type": "user",
    "uri": "spotify:user:spotifycharts"
  },
  "primary_color": null,
  "public": false,
  "snapshot_id": "Njc1MjczNzUyLDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDY1NmU=",
  "tracks": {
    "href": "https://api.spotify.com/v1/playlists/37i9dQZEVXbIPOivNiyjjS/tracks?offset=0&limit=100",
    "items": [
      {
        "added_at": "2021-05-25T16:02:32Z",
        "added_by": {
          "external_urls": {
            "spotify": "https://open.spotify.com/user/"
          },
          "href": "https://api.spotify.com/v1/users/",
          "id": "",
          "type": "user",
          "uri": "spotify:user:"
        },
        "is_local": false,
        "primary_color": null,
        "track": {
          "album": {
            "album_type": "album",
            "artists": [
              {
                "external_urls": {
                  "spotify": "https://open.spotify.com/artist/0lAWpj5szCSwM4rUMHYmrr"
                },
                "href": "https://api.spotify.com/v1/artists/0lAWpj5szCSwM4rUMHYmrr",
                "id": "0lAWpj5szCSwM4rUMHYmrr",
                "name": "Måneskin",
                "type": "artist",
                "uri": "spotify:artist:0lAWpj5szCSwM4rUMHYmrr"
              }
            ],
            "available_markets": [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BT",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GB",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "GY",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KI",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LI",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MH",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MV",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NR",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PS",
              "PT",
              "PW",
              "PY",
              "QA",
              "RO",
              "RS",
              "RU",
              "RW",
              "SA",
              "SB",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "SR",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TL",
              "TN",
              "TO",
              "TR",
              "TT",
              "TV",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VN",
              "VU",
              "WS",
              "XK",
              "ZA",
              "ZM",
              "ZW"
            ],
            "external_urls": {
              "spotify": "https://open.spotify.com/album/7KF1Ain9mYYlg5M46g0i4A"
            },
            "href": "https://api.spotify.com/v1/albums/7KF1Ain9mYYlg5M46g0i4A",
            "id": "7KF1Ain9mYYlg5M46g0i4A",
            "images": [
              {
                "height": 640,
                "url": "https://i.scdn.co/image/ab67616d0000b2733d4483341d2ef9d944e82186",
                "width": 640
              },
              {
                "height": 300,
                "url": "https://i.scdn.co/image/ab67616d00001e023d4483341d2ef9d944e82186",
                "width": 300
              },
              {
                "height": 64,
                "url": "https://i.scdn.co/image/ab67616d000048513d4483341d2ef9d944e82186",
                "width": 64
              }
            ],
            "name": "Teatro d'ira - Vol. I",
            "release_date": "2021-03-19",
            "release_date_precision": "day",
            "total_tracks": 8,
            "type": "album",
            "uri": "spotify:album:7KF1Ain9mYYlg5M46g0i4A"
          },
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/0lAWpj5szCSwM4rUMHYmrr"
              },
              "href": "https://api.spotify.com/v1/artists/0lAWpj5szCSwM4rUMHYmrr",
              "id": "0lAWpj5szCSwM4rUMHYmrr",
              "name": "Måneskin",
              "type": "artist",
              "uri": "spotify:artist:0lAWpj5szCSwM4rUMHYmrr"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RU",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW"
          ],
          "disc_number": 1,
          "duration_ms": 194786,
          "episode": false,
          "explicit": true,
          "external_ids": {
            "isrc": "ITB002100112"
          },
          "external_urls": {
            "spotify": "https://open.spotify.com/track/776AftMmFFAWUIEAb3lHhw"
          },
          "href": "https://api.spotify.com/v1/tracks/776AftMmFFAWUIEAb3lHhw",
          "id": "776AftMmFFAWUIEAb3lHhw",
          "is_local": false,
          "name": "ZITTI E BUONI",
          "popularity": 72,
          "preview_url": "https://p.scdn.co/mp3-preview/390d5808ce603ca425eb9a3cdf5629bdaa999950?cid=774b29d4f13844c495f206cafdad9c86",
          "track": true,
          "track_number": 1,
          "type": "track",
          "uri": "spotify:track:776AftMmFFAWUIEAb3lHhw"
        },
        "video_thumbnail": {
          "url": null
        }
      },
      {
        "added_at": "2021-05-25T16:02:32Z",
        "added_by": {
          "external_urls": {
            "spotify": "https://open.spotify.com/user/"
          },
          "href": "https://api.spotify.com/v1/users/",
          "id": "",
          "type": "user",
          "uri": "spotify:user:"
        },
        "is_local": false,
        "primary_color": null,
        "track": {
          "album": {
            "album_type": "single",
            "artists": [
              {
                "external_urls": {
                  "spotify": "https://open.spotify.com/artist/4kvCU3MzggM2piZCqvxj0x"
                },
                "href": "https://api.spotify.com/v1/artists/4kvCU3MzggM2piZCqvxj0x",
                "id": "4kvCU3MzggM2piZCqvxj0x",
                "name": "Go_A",
                "type": "artist",
                "uri": "spotify:artist:4kvCU3MzggM2piZCqvxj0x"
              }
            ],
            "available_markets": [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BT",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GB",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "GY",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KI",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LI",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MH",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MV",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NR",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PS",
              "PT",
              "PW",
              "PY",
              "QA",
              "RO",
              "RS",
              "RU",
              "RW",
              "SA",
              "SB",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "SR",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TL",
              "TN",
              "TO",
              "TR",
              "TT",
              "TV",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VN",
              "VU",
              "WS",
              "XK",
              "ZA",
              "ZM",
              "ZW"
            ],
            "external_urls": {
              "spotify": "https://open.spotify.com/album/4AQOhI7QMKq9vmHuzduPRk"
            },
            "href": "https://api.spotify.com/v1/albums/4AQOhI7QMKq9vmHuzduPRk",
            "id": "4AQOhI7QMKq9vmHuzduPRk",
            "images": [
              {
                "height": 640,
                "url": "https://i.scdn.co/image/ab67616d0000b27368f4797c1be17b662e2ee62e",
                "width": 640
              },
              {
                "height": 300,
                "url": "https://i.scdn.co/image/ab67616d00001e0268f4797c1be17b662e2ee62e",
                "width": 300
              },
              {
                "height": 64,
                "url": "https://i.scdn.co/image/ab67616d0000485168f4797c1be17b662e2ee62e",
                "width": 64
              }
            ],
            "name": "SHUM",
            "release_date": "2021-03-10",
            "release_date_precision": "day",
            "total_tracks": 2,
            "type": "album",
            "uri": "spotify:album:4AQOhI7QMKq9vmHuzduPRk"
          },
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/4kvCU3MzggM2piZCqvxj0x"
              },
              "href": "https://api.spotify.com/v1/artists/4kvCU3MzggM2piZCqvxj0x",
              "id": "4kvCU3MzggM2piZCqvxj0x",
              "name": "Go_A",
              "type": "artist",
              "uri": "spotify:artist:4kvCU3MzggM2piZCqvxj0x"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RU",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW"
          ],
          "disc_number": 1,
          "duration_ms": 172675,
          "episode": false,
          "explicit": false,
          "external_ids": {
            "isrc": "QM4TX2159313"
          },
          "external_urls": {
            "spotify": "https://open.spotify.com/track/7mEDVrAHDnQJStDo8jKJJm"
          },
          "href": "https://api.spotify.com/v1/tracks/7mEDVrAHDnQJStDo8jKJJm",
          "id": "7mEDVrAHDnQJStDo8jKJJm",
          "is_local": false,
          "name": "SHUM",
          "popularity": 73,
          "preview_url": "https://p.scdn.co/mp3-preview/d59eca273e728c7dce3351c87fb53d19c9a0808e?cid=774b29d4f13844c495f206cafdad9c86",
          "track": true,
          "track_number": 1,
          "type": "track",
          "uri": "spotify:track:7mEDVrAHDnQJStDo8jKJJm"
        },
        "video_thumbnail": {
          "url": null
        }
      },
      {
        "added_at": "2021-05-25T16:02:32Z",
        "added_by": {
          "external_urls": {
            "spotify": "https://open.spotify.com/user/"
          },
          "href": "https://api.spotify.com/v1/users/",
          "id": "",
          "type": "user",
          "uri": "spotify:user:"
        },
        "is_local": false,
        "primary_color": null,
        "track": {
          "album": {
            "album_type": "album",
            "artists": [
              {
                "external_urls": {
                  "spotify": "https://open.spotify.com/artist/0NFlmEJpgyF2sO4mtlwFfl"
                },
                "href": "https://api.spotify.com/v1/artists/0NFlmEJpgyF2sO4mtlwFfl",
                "id": "0NFlmEJpgyF2sO4mtlwFfl",
                "name": "The Backyardigans",
                "type": "artist",
                "uri": "spotify:artist:0NFlmEJpgyF2sO4mtlwFfl"
              }
            ],
            "available_markets": [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BT",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GB",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "GY",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KI",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LI",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MH",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MV",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NR",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PS",
              "PT",
              "PW",
              "PY",
              "QA",
              "RO",
              "RS",
              "RU",
              "RW",
              "SA",
              "SB",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "SR",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TL",
              "TN",
              "TO",
              "TR",
              "TT",
              "TV",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VN",
              "VU",
              "WS",
              "XK",
              "ZA",
              "ZM",
              "ZW"
            ],
            "external_urls": {
              "spotify": "https://open.spotify.com/album/6o4JpkccU6eGejGBoUw88E"
            },
            "href": "https://api.spotify.com/v1/albums/6o4JpkccU6eGejGBoUw88E",
            "id": "6o4JpkccU6eGejGBoUw88E",
            "images": [
              {
                "height": 640,
                "url": "https://i.scdn.co/image/ab67616d0000b27370738dbe34302194a05a6c27",
                "width": 640
              },
              {
                "height": 300,
                "url": "https://i.scdn.co/image/ab67616d00001e0270738dbe34302194a05a6c27",
                "width": 300
              },
              {
                "height": 64,
                "url": "https://i.scdn.co/image/ab67616d0000485170738dbe34302194a05a6c27",
                "width": 64
              }
            ],
            "name": "The Backyardigans",
            "release_date": "2005-07-12",
            "release_date_precision": "day",
            "total_tracks": 19,
            "type": "album",
            "uri": "spotify:album:6o4JpkccU6eGejGBoUw88E"
          },
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/0NFlmEJpgyF2sO4mtlwFfl"
              },
              "href": "https://api.spotify.com/v1/artists/0NFlmEJpgyF2sO4mtlwFfl",
              "id": "0NFlmEJpgyF2sO4mtlwFfl",
              "name": "The Backyardigans",
              "type": "artist",
              "uri": "spotify:artist:0NFlmEJpgyF2sO4mtlwFfl"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RU",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW"
          ],
          "disc_number": 1,
          "duration_ms": 87706,
          "episode": false,
          "explicit": false,
          "external_ids": {
            "isrc": "USA820500093"
          },
          "external_urls": {
            "spotify": "https://open.spotify.com/track/6uDBSDI9pDM7C4Gm0hc2hI"
          },
          "href": "https://api.spotify.com/v1/tracks/6uDBSDI9pDM7C4Gm0hc2hI",
          "id": "6uDBSDI9pDM7C4Gm0hc2hI",
          "is_local": false,
          "name": "Castaways",
          "popularity": 74,
          "preview_url": "https://p.scdn.co/mp3-preview/deb25a4e69ad36254cd091705f6fa4cbc28f85ca?cid=774b29d4f13844c495f206cafdad9c86",
          "track": true,
          "track_number": 3,
          "type": "track",
          "uri": "spotify:track:6uDBSDI9pDM7C4Gm0hc2hI"
        },
        "video_thumbnail": {
          "url": null
        }
      }
    ],
    "limit": 100,
    "next": null,
    "offset": 0,
    "previous": null,
    "total": 50
  },
  "type": "playlist",
  "uri": "spotify:playlist:37i9dQZEVXbIPOivNiyjjS"
}"""